#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.0.0.{build}

# Do not build on tags
skip_tags: false

# Start builds on tags only
skip_non_tags: false

# Skipping commits affecting specific files
skip_commits:
  files:
  - '**\AssemblyInfo.*'
  - 'CHANGELOG.md'

# 
pull_requests:
  do_not_increment_build_number: true
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
# clone directory
clone_folder: c:\projects\rocketbot2

# fetch repository as zip archive
shallow_clone: false

# set clone depth
# clone entire repository history if not defined
#clone_depth:  5

# environment variables

# build cache to preserve files/folders between builds
#cache:
#  - packages -> **\packages.config  # preserve packages directory in the root of build folder but will reset it if packages.config is modified
#  - '%LocalAppData%\NuGet\Cache'

# scripts that run after cloning repository
install:
 - git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos
 - sed -i "s#$(SolutionDir)#..#g" POGOProtos/POGOProtos.csproj
 - git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git FeroxRev
 - sed -i "s#$(SolutionDir)#..#g" FeroxRev/PokemonGo.RocketAPI.csproj

platform: x86

configuration: Release

build:
  verbosity: minimal

before_build:
  - nuget restore -OutputDirectory packages

before_package:

after_build:

build_script:

test: off
