version: 1.0.{build}
before_build:
- cmd: >-
    sed -i "s#$(SolutionDir)#.#g" PoGo.NecroBot.Logic.csproj

    nuget restore -OutputDirectory packages

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git FeroxRev

    sed -i "s#$(SolutionDir)#..#g" POGOProtos/POGOProtos.csproj

    sed -i "s#$(SolutionDir)#..#g" FeroxRev/PokemonGo.RocketAPI.csproj
build:
  verbosity: minimal