version: 1.0.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: x86
# environment variables
environment:
  SolutionDirectory: .
before_build:
- cmd: >-
    sed -i "s#$(SolutionDir)#.#g" PoGo.NecroBot.Logic.csproj

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/POGOProtos.git POGOProtos

    sed -i "s#$(SolutionDir)#..#g" POGOProtos/POGOProtos.csproj

    git clone -q --branch=master https://github.com/TheUnnamedOrganisation/FeroxRev.git FeroxRev

    sed -i "s#$(SolutionDir)#..#g" FeroxRev/PokemonGo.RocketAPI.csproj

    nuget restore -OutputDirectory packages
build:
  verbosity: minimal